name: StaffStick
version: "${version}"
main: com.spectrasonic.StaffStick.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    staffstick:
        permission: staffstick.give
        aliases: [ss]
permissions:
    staffstick.give:
        description: op
    staffstick.use:
        description: op
